In [ ]:
import cv2
import numpy as np

img1 = cv2.imread("spider.png")
img2 = cv2.imread("spider_img_snake_class.png")
diff = cv2.absdiff(img1, img2)
mask = cv2.cvtColor(diff, cv2.COLOR_BGR2GRAY)




th = 1
imask =  mask>th

canvas = np.zeros_like(img2, np.uint8)
canvas[imask] = img2[imask]


cv2.imwrite("result.png", mask)



True

In [ ]:
print(mask)

mask2 = np.where(mask > 3, 0*mask,2*mask)

cv2.imwrite("result.png", mask2)

print(mask2)



[[2 1 1 ... 1 1 0]
 [1 1 1 ... 3 1 1]
 [1 0 1 ... 2 2 1]
 ...
 [0 1 1 ... 1 1 2]
 [1 1 4 ... 1 2 3]
 [1 1 1 ... 1 1 0]]
[[4 2 2 ... 2 2 0]
 [2 2 2 ... 6 2 2]
 [2 0 2 ... 4 4 2]
 ...
 [0 2 2 ... 2 2 4]
 [2 2 0 ... 2 4 6]
 [2 2 2 ... 2 2 0]]


In [ ]:


img1 = cv2.imread("spider.png")
img2 = cv2.imread("spider_img_snake_class.png")
difference = cv2.subtract(img2, img1)
mask = cv2.cvtColor(diff, cv2.COLOR_BGR2GRAY)


Conv_hsv_Gray = cv2.cvtColor(difference, cv2.COLOR_BGR2GRAY)
ret, mask = cv2.threshold(Conv_hsv_Gray, 0, 255,cv2.THRESH_BINARY_INV |cv2.THRESH_OTSU)
difference[mask != 255] = [0, 0, 255]

# add the red mask to the images to make the differences obvious
img1[mask != 255] = [0, 0, 255]
img2[mask != 255] = [0, 0, 255]

# store images
cv2.imwrite('diffOverImage1.png', img1)
cv2.imwrite('diffOverImage2.png', img2)
cv2.imwrite('diff.png', difference)

True

In [ ]:
img1 = cv2.imread("snake.png")
img2 = cv2.imread("snake_img_spider_class.png")
difference = cv2.subtract(img2, img1)
mask = cv2.cvtColor(diff, cv2.COLOR_BGR2GRAY)


Conv_hsv_Gray = cv2.cvtColor(difference, cv2.COLOR_BGR2GRAY)
ret, mask = cv2.threshold(Conv_hsv_Gray, 0, 255,cv2.THRESH_BINARY_INV |cv2.THRESH_OTSU)
difference[mask != 255] = [0, 0, 255]

# add the red mask to the images to make the differences obvious
img1[mask != 255] = [0, 0, 255]
img2[mask != 255] = [0, 0, 255]

# store images
cv2.imwrite('diffOverImage1lol.png', img1)
cv2.imwrite('diffOverImage2lol.png', img2)
cv2.imwrite('diff2.png', difference)

True